name: spot
description: Chainable finders and better assertions for powerful widget tests.
version: 0.3.2
repository: https://github.com/passsy/spot
issue_tracker: https://github.com/passsy/spot/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.20.0

  # checks deps
  async: ^2.6.0
  meta: ^1.5.0
  test_api: '>=0.3.0 <0.6.0'

dev_dependencies:
  lint: '>=1.0.0 <3.0.0'
