name: spot
description: Chainable finders and better assertions for powerful widget tests.
version: 0.4.0
repository: https://github.com/passsy/spot
issue_tracker: https://github.com/passsy/spot/issues

environment:
  sdk: '>=3.0.0 <3.999.0'
  flutter: '>=3.10.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  checks: ^0.2.2
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.24.0

dev_dependencies:
  lint: ^2.0.0
